---
name: Ubuntu

# Build and run tests on Ubuntu

on:
  push:
    branches:
      - main
      - releasebranch_*
  pull_request:

permissions: {}

jobs:
  build:
    permissions:
      contents: read
      actions: read
    concurrency:
      group: >-
        ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}-build-${{
        matrix.name }}-${{ matrix.os }}
      cancel-in-progress: true

    runs-on: ${{ matrix.os }}
    env:
      PYTHONWARNINGS: always
    strategy:
      matrix:
        name:
          - "24.04"
          - minimum config

        include:
          - name: "24.04"
            os: ubuntu-24.04
            config: ubuntu-24.04
          # This is without optional things but it still keeps things useful,
          # so, e.g., without OpenMP, but with PDAL. Code or tests should be written
          # so that test pass even when these optional things are not present.
          - name: minimum config
            os: ubuntu-24.04
            config: ubuntu-24.04_without_x
      fail-fast: false

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Get dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget git gawk findutils
          LC_ALL=C.UTF-8 sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update -y
          xargs -a <(awk '! /^ *(#|$)/' ".github/workflows/apt.txt") -r -- \
              sudo apt-get install -y --no-install-recommends --no-install-suggests

      - name: Create installation directory
        run: |
          mkdir "${HOME}/install"

      - name: Set number of cores for compilation
        run: |
          echo "MAKEFLAGS=-j$(nproc)" >> "${GITHUB_ENV}"

      - name: Set LD_LIBRARY_PATH for compilation
        run: |
          echo "LD_LIBRARY_PATH=${HOME}/install/lib" >> "${GITHUB_ENV}"

      - name: Print build environment variables
        shell: bash -el {0}
        run: |
          printenv | sort
          gcc --version
          ldd --version

      - name: ccache
        uses: hendrikmuhs/ccache-action@d62db5f07c26379fc4b4e0916f098a92573c3b03 # v1.2.23
        with:
          create-symlink: true
          verbose: 2
          evict-old-files: 7d
          key: ${{ github.workflow }}-${{ matrix.config }}

      - name: Build
        env:
          # TODO: -pedantic-errors here won't go through ./configure (with GNU C)
          CFLAGS: -fPIC -Wvla -ffp-contract=off
          # TODO: -pedantic-errors here won't compile
          CXXFLAGS: -fPIC -ffp-contract=off
          MATRIX_CONFIG: ${{ matrix.config }}
        run: |
          ".github/workflows/build_${MATRIX_CONFIG}.sh" "${HOME}/install" -Werror

      - name: Add the bin directory to PATH
        run: |
          echo "${HOME}/install/bin" >> "${GITHUB_PATH}"

      - name: Print installed versions
        if: always()
        run: .github/workflows/print_versions.sh

      - name: Test executing of the grass command
        run: .github/workflows/test_simple.sh

      - name: Pack the installation directory
        run: |
          tar -C "${HOME}" --zstd -cf grass-install.tar.zst install

      - name: Upload the installation directory
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: grass-install-${{ matrix.config }}
          if-no-files-found: error
          path: grass-install.tar.zst
          # Only needed for the test jobs in the same workflow run.
          retention-days: 1

  ubuntu:
    needs: build
    permissions:
      contents: read
      actions: read
    concurrency:
      group: >-
        ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}-${{
        matrix.name }}-${{ matrix.os }}-${{ matrix.test-group }}
      cancel-in-progress: true

    runs-on: ${{ matrix.os }}
    env:
      PYTHONWARNINGS: always
    strategy:
      matrix:
        name:
          - "24.04"
          - minimum config

        # Only run tests for the folders included in the test group of this
        # matrix job. Groups are sized to run in roughly the same time and
        # are labeled by their largest member.
        test-group:
          - temporal
          - raster
          - python
          - vector

        include:
          - name: "24.04"
            os: ubuntu-24.04
            config: ubuntu-24.04
          - name: minimum config
            os: ubuntu-24.04
            config: ubuntu-24.04_without_x
          # All root folders that could contain tests are:
          #   db display doc docker general gui
          #   imagery lib misc ps python raster raster3d scripts
          #   temporal testsuite utils vector visualization
          # Each folder must be in exactly one group.
          #
          # In order to split test executions, all these root folders are
          # added as excluded folders, then items included for this matrix
          # job are removed from that exclusion list.
          #
          # Using folded YAML multiline string block chomping (>-) to replace
          # newlines with spaces, and strip newline at end.
          # See https://yaml-multiline.info/
          - test-group: temporal
            extra-include: temporal
          - test-group: raster
            extra-include: raster raster3d
          - test-group: python
            extra-include: python scripts
          - test-group: vector
            extra-include: >-
              db display doc docker general gui
              imagery lib misc ps
              testsuite utils vector visualization
      fail-fast: false

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Invert inclusion list to an exclusion list
        id: get-exclude
        run: |
          array=(db display doc docker general gui \
          imagery lib misc ps python raster raster3d scripts \
          temporal testsuite utils vector visualization)
          echo "Complete set of folders that can be included:"
          echo "${array[@]}"
          # shellcheck disable=SC2206
          delete=( ${DELETE_ARRAY} )
          echo "Included folders to remove from the complete set:"
          echo "${delete[@]}"
          for target in "${delete[@]}"; do
            for i in "${!array[@]}"; do
              if [[ ${array[i]} = "${target}" ]]; then
                unset 'array[i]'
              fi
            done
          done
          unset new_array
          for i in "${!array[@]}"; do
              new_array+=( "${array[i]}" )
          done
          echo "Excluded folders:"
          echo "${new_array[@]}"
          printf -v extra_exclude './%s/* ' "${new_array[@]}"
          echo "Exclusion string to add to gunittest config"
          echo "${extra_exclude}"
          echo "extra-exclude=${extra_exclude}" >> "${GITHUB_OUTPUT}"
        env:
          DELETE_ARRAY: ${{ matrix.extra-include }}

      - name: Add extra exclusions to a gunittest config file
        run: |
          sed "s:exclude =:exclude = ${STEPS_GET_EXCLUDE_OUTPUTS_EXTRA_EXCLUDE}:g" .gunittest.cfg > .gunittest.extra.cfg
          cat .gunittest.extra.cfg
        env:
          STEPS_GET_EXCLUDE_OUTPUTS_EXTRA_EXCLUDE: ${{ steps.get-exclude.outputs.extra-exclude }}

      - name: Get dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget git gawk findutils
          LC_ALL=C.UTF-8 sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update -y
          xargs -a <(awk '! /^ *(#|$)/' ".github/workflows/apt.txt") -r -- \
              sudo apt-get install -y --no-install-recommends --no-install-suggests

      - name: Download the installation directory
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: grass-install-${{ matrix.config }}

      - name: Unpack the installation directory
        run: |
          tar -C "${HOME}" --zstd -xf grass-install.tar.zst

      - name: Set LD_LIBRARY_PATH
        run: |
          echo "LD_LIBRARY_PATH=${HOME}/install/lib" >> "${GITHUB_ENV}"

      - name: Add the bin directory to PATH
        run: |
          echo "${HOME}/install/bin" >> "${GITHUB_PATH}"

      - name: Print installed versions
        if: always()
        run: .github/workflows/print_versions.sh

      - name: Test executing of the grass command
        run: .github/workflows/test_simple.sh

      - name: Cache GRASS Sample Dataset
        id: cached-data
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: sample-data/nc_spm_full_v2beta1.tar.gz
          key: nc_spm_full_v2beta1.tar.gz
          enableCrossOsArchive: true

      - name: Download GRASS Sample Dataset
        if: steps.cached-data.outputs.cache-hit != 'true'
        run: |
          mkdir -p sample-data
          curl -L "${SAMPLE_DATA}" -o sample-data/nc_spm_full_v2beta1.tar.gz
        env:
          SAMPLE_DATA: "https://grass.osgeo.org/sampledata/north_carolina/\
            nc_spm_full_v2beta1.tar.gz"

      - name: Save GRASS Sample Dataset to cache
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        # Fix: do not write to cache on pull_request events to prevent cache poisoning.
        # Fork PRs can otherwise overwrite shared cache keys used by main branch runs.
        if: steps.cached-data.outputs.cache-hit != 'true' && github.event_name != 'pull_request'
        with:
          path: sample-data/nc_spm_full_v2beta1.tar.gz
          key: nc_spm_full_v2beta1.tar.gz

      - name: Run tests
        run: .github/workflows/test_thorough.sh --config .gunittest.extra.cfg
        env:
          SAMPLE_DATA_URL: "file://${{ github.workspace }}/sample-data/\
            nc_spm_full_v2beta1.tar.gz"

      - name: Make HTML test report available
        if: ${{ always() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: testreport-${{ matrix.os }}-${{ matrix.config }}-${{ matrix.test-group }}
          path: testreport
          retention-days: 3

  pytest:
    needs: build
    concurrency:
      group: >-
        ${{ github.workflow }}-pytest-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}-${{
        matrix.os }}-${{ matrix.python-version }}
      cancel-in-progress: true

    strategy:
      matrix:
        os:
          - ubuntu-24.04
        python-version:
          - "3.11"
          - "3.13"
      fail-fast: true

    runs-on: ${{ matrix.os }}
    env:
      FORCE_COLOR: 1 # for software including pip: https://force-color.org/
      CLICOLOR_FORCE: 1 # for other software including ninja: https://bixense.com/clicolors/
      PYTHONWARNINGS: always

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip # zizmor: ignore[cache-poisoning] This workflow is not used for release artifacts
          allow-prereleases: true

      - name: Install non-Python dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget git gawk findutils
          LC_ALL=C.UTF-8 sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update -y
          xargs -a <(awk '! /^ *(#|$)/' ".github/workflows/apt.txt") -r -- \
              sudo apt-get install -y --no-install-recommends --no-install-suggests

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --break-system-packages -r .github/workflows/python_requirements.txt
          pip install --break-system-packages -r .github/workflows/optional_requirements.txt
          pip install --break-system-packages pytest pytest-timeout \
              pytest-github-actions-annotate-failures pytest-xdist pytest-cov

      - name: Download the installation directory
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          # The full config build for this platform.
          name: grass-install-ubuntu-24.04

      - name: Unpack the installation directory
        run: |
          tar -C "${HOME}" --zstd -xf grass-install.tar.zst

      - name: Add the bin directory to PATH
        run: |
          echo "${HOME}/install/bin" >> "${GITHUB_PATH}"

      - name: Print installed versions
        if: always()
        run: .github/workflows/print_versions.sh

      - name: Test executing of the grass command
        run: .github/workflows/test_simple.sh

      - name: Run pytest with multiple workers in parallel
        run: |
          PYTHONPATH="$(grass --config python_path):${PYTHONPATH}"
          LD_LIBRARY_PATH="$(grass --config path)/lib:${LD_LIBRARY_PATH}"
          INITIAL_GISBASE="$(grass --config path)"
          INITIAL_PWD="${PWD}"
          export PYTHONPATH
          export LD_LIBRARY_PATH
          export INITIAL_GISBASE
          export INITIAL_PWD
          pytest \
            @.github/workflows/pytest_args_ci.txt \
            @.github/workflows/pytest_args_cov.txt \
            @.github/workflows/pytest_args_parallel.txt \
            --junitxml=pytest.xdist.junit.xml \
            -k 'not testsuite'
        env:
          OMP_NUM_THREADS: 1

      - name: Run pytest with a single worker (for tests marked with needs_solo_run)
        run: |
          PYTHONPATH="$(grass --config python_path):${PYTHONPATH}"
          LD_LIBRARY_PATH="$(grass --config path)/lib:${LD_LIBRARY_PATH}"
          INITIAL_GISBASE="$(grass --config path)"
          INITIAL_PWD="${PWD}"
          export PYTHONPATH
          export LD_LIBRARY_PATH
          export INITIAL_GISBASE
          export INITIAL_PWD
          pytest \
            @.github/workflows/pytest_args_ci.txt \
            @.github/workflows/pytest_args_cov.txt \
            @.github/workflows/pytest_args_not_parallel.txt \
            --junitxml=pytest.needs_solo_run.junit.xml \
            -k 'not testsuite'
      - name: Run pytest with a single worker (for gunittest-based tests)
        run: |
          PYTHONPATH="$(grass --config python_path):${PYTHONPATH}"
          LD_LIBRARY_PATH="$(grass --config path)/lib:${LD_LIBRARY_PATH}"
          INITIAL_GISBASE="$(grass --config path)"
          INITIAL_PWD="${PWD}"
          export PYTHONPATH
          export LD_LIBRARY_PATH
          export INITIAL_GISBASE
          export INITIAL_PWD
          pytest \
            @.github/workflows/pytest_args_cov.txt \
            @.github/workflows/pytest_args_gunittest.txt \
            --junitxml=pytest.gunittest.junit.xml
      - name: Fix non-standard installed script paths in coverage data
        run: |
          PYTHONPATH="$(grass --config python_path):${PYTHONPATH}"
          LD_LIBRARY_PATH="$(grass --config path)/lib:${LD_LIBRARY_PATH}"
          INITIAL_GISBASE="$(grass --config path)"
          INITIAL_PWD="${PWD}"
          export PYTHONPATH
          export LD_LIBRARY_PATH
          export INITIAL_GISBASE
          export INITIAL_PWD
          python utils/coverage_mapper.py
          coverage combine
          coverage html

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          exclude: gui
          flags: pytest-python-${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          verbose: true
          flags: pytest-python-${{ matrix.python-version }}
          name: pytest-python-${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Make python-only code coverage test report available
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: python-codecoverage-report-${{ matrix.os }}-${{ matrix.python-version }}
          path: coverage_html_report
          retention-days: 1

  python-checks:
    name: Python Code Quality Checks
    needs: build

    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}-${{
        github.event_name == 'pull_request' &&
        github.head_ref || github.sha }}
      cancel-in-progress: true

    strategy:
      matrix:
        include:
          - os: ubuntu-24.04

    env:
      # renovate: datasource=python-version depName=python
      PYTHON_VERSION: "3.14"
      MIN_PYTHON_VERSION: "3.11"
      # renovate: datasource=pypi depName=flake8
      FLAKE8_VERSION: "7.3.0"
      # renovate: datasource=pypi depName=pylint
      PYLINT_VERSION: "4.0.6"
      # renovate: datasource=pypi depName=bandit
      BANDIT_VERSION: "1.9.4"
      # renovate: datasource=pypi depName=ruff
      RUFF_VERSION: "0.15.17"

    runs-on: ${{ matrix.os }}
    permissions:
      security-events: write

    steps:
      - name: Versions
        run: |
          echo "OS: ${MATRIX_OS}"
          echo "Python: ${PYTHON_VERSION}"
          echo "Minimal Python version: ${MIN_PYTHON_VERSION}"
          echo "Flake8: ${FLAKE8_VERSION}"
          echo "Pylint: ${PYLINT_VERSION}"
          echo "Bandit: ${BANDIT_VERSION}"
          echo "Ruff: ${RUFF_VERSION}"
        env:
          MATRIX_OS: ${{ matrix.os }}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip # zizmor: ignore[cache-poisoning] Not creating release artifacts, less of a concern here
      - name: Upgrade pip
        run: python -m pip install --break-system-packages --upgrade pip

      - name: Install Ruff
        run: pip install --break-system-packages "ruff==${RUFF_VERSION}"
      - name: Run Ruff (output annotations on fixable errors)
        run: ruff check --output-format=github . --preview --unsafe-fixes
        continue-on-error: true
      - name: Run Ruff (apply fixes for suggestions)
        run: ruff check . --preview --fix --unsafe-fixes
      - name: Run `ruff format` showing diff without failing
        continue-on-error: true
        if: ${{ !cancelled() }}
        run: ruff format --diff
      - name: Run `ruff format` fixing files
        # Run `ruff format` even when `ruff check` fixed files: fixes can require formatting
        if: ${{ !cancelled() }}
        run: ruff format
      - name: Create and uploads code suggestions to apply for Ruff
        # Will fail fast here if there are changes required
        id: diff-ruff
        # To run after ruff step exits with failure when rules don't have fixes available
        if: ${{ !cancelled() }}
        uses: ./.github/actions/create-upload-suggestions
        with:
          tool-name: ruff
          # To keep repo's file structure in formatted changes artifact
          extra-upload-changes: pyproject.toml

      - name: Install non-Python dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget git gawk findutils
          LC_ALL=C.UTF-8 sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update -y
          xargs -a <(awk '! /^ *(#|$)/' ".github/workflows/apt.txt") -r -- \
          sudo apt-get install -y --no-install-recommends --no-install-suggests

      - name: Install Python dependencies
        run: |
          pip install --break-system-packages -r .github/workflows/python_requirements.txt
          pip install --break-system-packages -r .github/workflows/optional_requirements.txt
          pip install --break-system-packages --user pipx
          pipx ensurepath
          pipx install "flake8==${FLAKE8_VERSION}"
          pipx install "pylint==${PYLINT_VERSION}"
          pipx inject pylint -r .github/workflows/python_requirements.txt -r .github/workflows/optional_requirements.txt
          pipx install "bandit[sarif]==${BANDIT_VERSION}"

      - name: Run Flake8
        run: |
          flake8 --count --statistics --show-source --jobs="$(nproc)" .

      - name: Run Flake8 on additional files
        run: |
          flake8 --count --statistics --show-source --jobs="$(nproc)" python/grass/{script,jupyter}/testsuite/

      - name: Bandit Vulnerability Scan
        run: |
          bandit -c pyproject.toml -iii -r . -f sarif -o bandit.sarif --exit-zero

      - name: Upload Bandit Scan Results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: bandit.sarif
          path: bandit.sarif

      - name: Upload SARIF File into Security Tab
        uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
        with:
          sarif_file: bandit.sarif

      - name: Download the installation directory
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          # The full config build for this platform.
          name: grass-install-ubuntu-24.04

      - name: Unpack the installation directory
        run: |
          tar -C "${HOME}" --zstd -xf grass-install.tar.zst

      - name: Add the bin directory to PATH
        run: |
          echo "${HOME}/install/bin" >> "${GITHUB_PATH}"

      # - name: Run Pylint on grass package
      #   # Until slower checks (like similarity) are enabled, running in one step is faster
      #   if: false
      #   run: |
      #     PYTHONPATH="$(grass --config python_path):$PYTHONPATH"
      #     LD_LIBRARY_PATH="$(grass --config path)/lib:$LD_LIBRARY_PATH"
      #     export PYTHONPATH
      #     export LD_LIBRARY_PATH
      #     pylint --persistent=no --py-version=${{ env.MIN_PYTHON_VERSION }} --jobs="$(nproc)" grass

      # - name: Run Pylint on other files using pytest
      #   # Until slower checks (like similarity) are re-enabled, running in one step is faster
      #   if: false
      #   run: |
      #     pipx inject --include-apps pylint pytest
      #     pipx inject pylint pytest-pylint pytest-github-actions-annotate-failures pytest-timeout
      #     PYTHONPATH="$(grass --config python_path):$PYTHONPATH"
      #     LD_LIBRARY_PATH="$(grass --config path)/lib:$LD_LIBRARY_PATH"
      #     export PYTHONPATH
      #     export LD_LIBRARY_PATH
      #     pytest --pylint -m pylint --pylint-jobs="$(nproc)" \
      #       --pylint-ignore-patterns="${{ env.PylintIgnore }}"
      #   env:
      #     PylintIgnore: "python/.*,gui/.*"

      # - name: Run Pylint on wxGUI
      #   # Until slower checks (like similarity) are re-enabled, running in one step is faster
      #   if: false
      #   run: |
      #     PYTHONPATH="$(grass --config python_path):$PYTHONPATH"
      #     LD_LIBRARY_PATH="$(grass --config path)/lib:$LD_LIBRARY_PATH"
      #     export PYTHONPATH
      #     export LD_LIBRARY_PATH
      #     pylint --persistent=no --py-version="${MIN_PYTHON_VERSION}" --jobs="$(nproc)" gui

      - name: Run Pylint all in one pass
        run: |
          PYTHONPATH="$(grass --config python_path):$PYTHONPATH"
          LD_LIBRARY_PATH="$(grass --config path)/lib:$LD_LIBRARY_PATH"
          export PYTHONPATH
          export LD_LIBRARY_PATH
          pylint --persistent=no --py-version="${MIN_PYTHON_VERSION}" --jobs="$(nproc)" .

      - name: Test compiling example modules
        # The source tree is not built here, so compile against the installed
        # tree like an addon, which is also how users compile these examples.
        run: |
          MODULE_TOPDIR="$(grass --config path)"
          ( cd doc/examples/raster/r.example/ && make MODULE_TOPDIR="${MODULE_TOPDIR}" )
          ( cd doc/examples/vector/v.example/ && make MODULE_TOPDIR="${MODULE_TOPDIR}" )

  build-and-test-success:
    name: Build & Test Result
    needs:
      - build
      - ubuntu
    if: ${{ always() }}
    uses: ./.github/workflows/verify-success.yml
    with:
      needs_context: ${{ toJson(needs) }}

  pytest-success:
    name: pytest Result
    needs:
      - pytest
    if: ${{ always() }}
    uses: ./.github/workflows/verify-success.yml
    with:
      needs_context: ${{ toJson(needs) }}

  python-success:
    name: Python Code Quality Result
    needs:
      - python-checks
    if: ${{ always() }}
    uses: ./.github/workflows/verify-success.yml
    with:
      needs_context: ${{ toJson(needs) }}
